[theme]
primaryColor="#004080"  # A deep blue
backgroundColor="#FFFFFF"  # White background
secondaryBackgroundColor="#F0F2F6"  # Light gray for sidebars/elements
textColor="#333333"  # Dark gray for text
font="sans serif"
